### ISSUE TITLE
; required after if statement

### ISSUE THREAD

**Issue by stefanak-michal** [thingsdb/ThingsDB#373]
![image](https://github.com/thingsdb/ThingsDB/assets/5502917/65779b75-9a83-49c9-b279-a13d14d62217)

When I add `;` after `}` it works. It is intentional? https://docs.thingsdb.io/v1/overview/statements/#ifelse doesn't mention it.

Tested on ThingsDB version from branch https://github.com/thingsdb/ThingsDB/tree/lws

**Comment by joente** [comment]
The documentation contained an error _(fixed now)_. In ThingsDB, code blocks `{ ... }` are treated as statements and require a semicolon `;` at the end. While the example code you saw functioned, it technically wasn't correct because the semicolon was missing after the closing curly brace. The semicolon is only optional for the last statement

**Comment by stefanak-michal** [comment]
Oh yeah ..code blocks has to be terminated with `;` .. I didn't realize or I forget ..thanks for updating docs.
